### ISSUE TITLE
Add possibility to set naming to [name].webp, not only [name].[ext].webp

### ISSUE THREAD

**Issue by alizhdanov** [jiangtao/webp-webpack-plugin#7]
Hello, is it possible to add possibility to generate `webp` images with such file name ` [name].webp` ?

### What we have now:

* Original image - `my-super-image.jpg`
* Generated by plugin - `my-super-image.jpg.webp`

### What I'm proposing:

* Original image - `my-super-image.jpg`
* Generated by plugin - `my-super-image.webp`

Thanks.

**Comment by jiangtao** [comment]
ok. I will finish it and publish new version.
