### ISSUE TITLE
Download of https://dl.bintray.com/lovell/sharp/... failed 

### ISSUE THREAD

**Issue by webaifei** [jiangtao/webp-webpack-plugin#9]
## DESC
when use webp-webpack-plugin
ERROR: Download of https://dl.bintray.com/lovell/sharp/... failed 
And i update sharp to 0.21.0, the issue can be resolved. Could you update your sharp denpency?
Thanks.
### ENV
vue-cli2 
node v8.12.0
npm 6.4.1

OS Platform:
MacBook Pro 10.13.6

webpack Version:
^3.6.0
### code

```js
 // webp图片格式
        new WebPWebpackPlugin({
            match: /(jpe?g|png)$/,
            format: "[name].webp"
        }),
```

### error message
```
ERROR: Download of https://dl.bintray.com/lovell/sharp/... failed 
```
### more description

i update the sharp version to ^0.21.0。

**Comment by jiangtao** [comment]
挂上vpn试试？
